// pages/Components/Container.tsx
import { useEffect, ReactNode, useState } from "react";
import styles from "./Container.module.css";

const Container = (props: {
  column?: Boolean | null;
  fluid?: Boolean | null;
  row?: Boolean | null;
  justifyContent?: String | null;
  columnIfMd?: Boolean | null;
  rowIfMd?: Boolean | null;
  rowIfSm?: Boolean | null;
  columnIfSm?: Boolean | null;
  alignItems?: String | null;
  size?: Number | null;
  className?: string | null;
  children: ReactNode;
}) => {
  const [cssClasses, setCssClasses] = useState<Array<string>>([]);
  useEffect(() => {
    const cssClassesInner = [];

    if (props.className){
      cssClassesInner.push(props.className);
    }
    if (props.column) {
      cssClassesInner.push(styles.column);
    }
    if (props.row) {
      cssClassesInner.push(styles.row);
    }
    if (props.columnIfMd) {
      cssClassesInner.push(styles['column-if-md']);
    }
    if (props.rowIfMd) {
      cssClassesInner.push(styles['row-if-md']);
    }
    if (props.rowIfSm) {
      cssClassesInner.push(styles['row-if-sm']);
    }
    if (props.columnIfSm) {
      cssClassesInner.push(styles['column-if-sm']);
    }
    if (props.fluid) {
      cssClassesInner.push(styles.container);
    }
    if (props.justifyContent) {
      switch (props.justifyContent) {
        case "center":
          cssClassesInner.push(styles['justify-content-center']);
          break;
        default:
          break;
      }
    }
    if (props.alignItems) {
      switch (props.alignItems) {
        case "center":
          cssClassesInner.push(styles['align-items-center']);
          break;
        default:
          break;
      }
    }
    if (props.size) {
      cssClassesInner.push(styles[`item-${props.size}`]);
    }
    setCssClasses(cssClassesInner);
  }, [props]);

  return <div className={cssClasses.join(" ")}>{props.children}</div>;
};

export default Container;

// src/components/Container.vue
<template>
<div :class="cssClasses">
  <slot> </slot>
</div>  
</template>

<script>
export default {
  props: {
    column: Boolean,
    fluid: Boolean,
    row: Boolean,
    justifyContent: String,
    columnIfMd: Boolean,
    rowIfMd: Boolean,
    rowIfSm: Boolean,
    columnIfSm: Boolean,
    alignItems: String,
    size: Number
  },
  data() {
    return {
      cssClasses: []
      
    }
  },
  mounted() {
    this.cssClasses = this.computeCssClasses();
  },
  methods: {
    computeCssClasses() {
      const cssClasses = [];

      if(this.$props.column) {
        cssClasses.push('column');
      }
      if(this.$props.row) {
        cssClasses.push('row');
      }
      if(this.$props.columnIfMd) {
        cssClasses.push('column-if-md');
      }
      if(this.$props.rowIfMd) {
        cssClasses.push('row-if-md');
      }
      if(this.$props.rowIfSm) {
        cssClasses.push('row-if-sm');
      }
      if(this.$props.columnIfSm) {
        cssClasses.push('column-if-sm');
      }
      if(this.$props.fluid) {
        cssClasses.push('container')
      }
      if(this.$props.justifyContent) {
        switch (this.$props.justifyContent) {
          case 'center':
            cssClasses.push('justify-content-center');
            break;
          default:
            break;
        }
      }
      if(this.$props.alignItems) {
        console.log(this.$props.alignItems);

        switch (this.$props.alignItems) {
          case 'center':
            cssClasses.push('align-items-center');
            break;
          default:
            break;
        }
      }
      if(this.$props.size) {
          cssClasses.push(`item-${this.size}`);
      }
      return cssClasses;
    }
  }  
}
</script>

<style scoped>

.container.column {
  display: flex;
  flex-wrap: wrap;
  flex-direction: column;
}

.container.align-items-center {
  align-items: center;
}

.container.justify-content-center {
  justify-content: center;
}

@media screen and (max-width: 950px) {
  .container {
    padding: 4px 2px 4px 2px !important;
  }
}
@media screen and (min-width: 950px) {
  .container {
    padding: 20px;
    display: flex;
  }

  .container .item-2 {
    flex: 2;
  }
  .container .item-6 {
    flex: 6;
  }
}

@media screen and (max-width: 1250px) {
  .column-if-md {
    flex-flow: column !important;
  }
  .row-if-md {
    flex-flow: row !important;
  }
}
</style>
